### ISSUE TITLE
Shows Values not Labels

### ISSUE THREAD

**Issue by jencastrodoesstuff** [digidem/mapeo-desktop#412] opened 2020-09-02 19:40 UTC
**Describe the bug**
Show "values" in fields when options are selected

**Can you do the same thing twice?**
yes 
test 1
<img width="715" alt="Screen Shot 2020-09-02 at 3 09 59 PM" src="https://user-images.githubusercontent.com/33264095/92028352-e3d83800-ed31-11ea-809f-9efd61e84fe3.png">
<img width="322" alt="Screen Shot 2020-09-02 at 3 05 54 PM" src="https://user-images.githubusercontent.com/33264095/92028353-e470ce80-ed31-11ea-9f87-5280e6e5d0fa.png">
<img width="406" alt="Screen Shot 2020-09-02 at 3 05 48 PM" src="https://user-images.githubusercontent.com/33264095/92028354-e470ce80-ed31-11ea-811b-02743482ae4b.png">

test 2
<img width="624" alt="Screen Shot 2020-09-02 at 3 25 32 PM" src="https://user-images.githubusercontent.com/33264095/92028403-f9e5f880-ed31-11ea-82c7-49f994a79ed1.png">
![WhatsApp Image 2020-09-02 at 3 30 46 PM](https://user-images.githubusercontent.com/33264095/92028429-09654180-ed32-11ea-9a88-a6b3946fd9dd.jpeg)

<img width="369" alt="Screen Shot 2020-09-02 at 3 26 07 PM" src="https://user-images.githubusercontent.com/33264095/92028407-fd797f80-ed31-11ea-87bc-fd61ab1192f6.png">

**Expected behavior**
Should always display "label"

**Screenshots**

**Desktop:**
 - OS: Catelina

**Smartphone:**
 - Device: Jen's Galaxy S10+
 
**Mapeo Version:**
 - Desktop v5.4.0.beta7
 - Mobile v5.0.3.879
 
**Additional context**

**Comment by jencastrodoesstuff** [comment] 2020-09-02 19:47
This may or may not be related to https://github.com/digidem/mapeo-mobile/issues/455

**Comment by okdistribute** [comment] 2020-09-03 17:27
This was also reported to be the case with Reports.

The code that does the label/value conversation is unfortunately not shared between Mobile and Desktop. @gmaclennan at some point we could do this using a shared @mapeo/observations module, which I proposed in the mapeo core RFC 003.

**Comment by gmaclennan** [comment] 2020-09-03 17:36
Hi @jencastrodoesstuff from what I can make out from the screen shots, it looks like the label is showing for multi-select, but not for single-select? Is that correct? The code is in place on Desktop so this _should_ work (e.g. it is not a feature that we have not implemented yet) so this is a bug.

The code for this has not been added to Mapeo Mobile yet.

@okdistribute I'd like to think about how Mapeo Mobile and Desktop could share more code, including components (using react-native-web) as well as logic (I think it would be hard to abstract logic that is closely tied to display components into a separate module, since it could really slow down development when needing to change things, and hard to have a clear separation between logic to prepare a view of data, and a view of data in a component). I think moving Desktop and Mobile into the same repo is one option, but would take several days of configuring build tools. Manyverse is moving towards doing this (last time I checked), and there a few other examples out there.

**Comment by jencastrodoesstuff** [comment] 2020-09-03 17:47
@gmaclennan  the label is not displaying for either multi or single select.
In my example, the select on location list was originally scripted as "Otro" so I had to designate it as the value when implementing this in order to maintain consistancy with exsisting data

**Comment by okdistribute** [comment] 2020-09-03 18:39
@gmaclennan makes sense. I think to start out we would go a long way to have an object oriented model for all of our database entries - in this case, relevant objects would be Observation and Field - and the logic for parsing and rendering the Label or value could be in there

**Comment by okdistribute** [comment] 2020-09-14 01:07
@jencastrodoesstuff can you send me the configuration that caused this issue? I'm not able to reproduce on my end in 5.4.0-beta.7

**Comment by jencastrodoesstuff** [comment] 2020-09-14 16:07
*Jen Castro*
*(Remote from Montreal)*
*Program Coordination - **Digital Democracy*
Tel Perú:  +51(1)7007968 , Canada: +15144009274 , WhatsApp: +150231892622,
Skype (por cita):  live:jen_5964

**Pido disculpas por cualquier error gramática u ortográfica. Estoy en el
proceso de mejorar mi nivel de castellano y aprecio su paciencia.

**Comment by jencastrodoesstuff** [comment] 2020-09-14 16:46
sadly  I can't drp the .mappeosetting file because github has limited file formats..

it's here: [ECA's confog folder on GDrive](https://drive.google.com/file/d/17SUo65m-rXGgXVsr5h3G-yVikNMeEakR/view?usp=sharing )

**Comment by okdistribute** [comment] 2020-09-14 16:49
thanks jen!

**Comment by okdistribute** [comment] 2020-09-14 20:52
![Screenshot from 2020-09-14 13-49-08](https://user-images.githubusercontent.com/633012/93136653-21718500-f691-11ea-80ca-234961629e13.png)

still not able to reproduce on both dev and producation versions; :-\ I wonder if this is something unrelated, perhaps based on outdated presets being used by Mapeo Desktop somehow? Was there anything peculiar that happened before trying to do this? If you restart mapeo and edit again (with 5.4.0-beta.6) do you still see this problem?

**Comment by okdistribute** [comment] 2020-09-16 23:47
Is it possible that the old field is attached to the data somehow and I won't be able to replicate this without looking at your data? *rubs chin in thought*

**Closed** 2020-09-28 19:17 UTC
Labels: bug
