### ISSUE TITLE
Mapeo will not quit on MacOS

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#398] opened 2020-08-17 17:29 UTC
**Describe the bug**
When I quite Mapeo (on MacOS) it stays open. Closing the window does seem to quit the app. This is possibly because of a variable that is not being garbage collected / set to `null`.

**Desktop:**
 - OS: MacOS 10.15.6
 
**Mapeo Version:**
 - Desktop 5.4.0-beta.5

**Comment by okdistribute** [comment] 2020-08-20 00:21
I am using Mac OS 10.12.6, I can't reproduce this. Did you do anything in particular before closing? Could it be related to the MacOS version?

**Comment by okdistribute** [comment] 2020-08-20 19:33
from @gmaclennan 
> hey I think one of the issues with quit might be just that it takes a long time to quit. The beforeQuit function means that the main window is not closed until after everything is cleaned up. This works as you might expect if you quit the app by closing the main window (window closes, closing window shows, then app quits) but if you quit by the menu --> quit option then it seems like it does nothing (main window stays open, and I think maybe hides the closing window) and can take a whilte

**Comment by okdistribute** [comment] 2020-08-21 04:45
@gmaclennan will you have time to work on this? If not I can take a look next week; I have an extra mac I can use.

**Comment by gmaclennan** [comment] 2020-08-25 14:41
@okdistribute not in the next week or two no, realistically.

**Comment by okdistribute** [comment] 2020-08-25 18:33
Thanks for the reply - I am updating to 10.15 on my mac now to test

**Closed** 2020-09-28 17:46 UTC
Labels: bug
