### ISSUE TITLE
(Front) Make header text in closing.html a translatable string

### ISSUE THREAD

**Issue by emreiser** [digidem/mapeo-desktop#509] opened 2021-07-21 18:02 UTC
**Describe the bug**
The text displayed when quitting Mapeo is currently hard-coded and not available as a translatable string. See: https://github.com/digidem/mapeo-desktop/blob/master/static/closing.html#L46

<img width="597" alt="Captura de Tela 2021-07-21 às 1 50 07 PM" src="https://user-images.githubusercontent.com/3493841/126536096-ee1e8ee0-b09c-4c7d-b920-c718d85bea07.png">
 
**Mapeo Version:**
 - Desktop 5.4.0-beta.15 

Points: 8

**Comment by bthrall** [comment] 2021-11-12 22:07
This looks like a duplicate of #429

**Comment by achou11** [comment] 2021-11-12 22:08
Ah yes you're right @bthrall. Thanks for noting! We'll close the other one and defer to this one :)

**Closed** 2021-12-14 23:38 UTC
Labels: bug, nuggets
