### ISSUE TITLE
osm-p2p "Save"-Sidebar-Dialog

### ISSUE THREAD

**Issue by LukasWillin** [digidem/mapeo-desktop#145] opened 2018-04-30 10:00 UTC
Hello again Mapeo Dev Team

I got a question about the save functionality in Mapeo. Even though you use your osm-p2p technology and the demo video uses the 'Save' button - the dialog still states that changes are stored online and can be viewed and reviewed by all users and services using open street maps. 
My guess is that this part of the application just hasnt been changed yet and nothing goes online once you connect to the internet. Is that correct?

If all data is only stored in a local db and synced via a file I would suggest changing the dialog to something like: "All changes will be stored on the local p2p-db. You can sync your data with others later via the synchronize button".

I find the current dialog-text to be quiet misleading (especially for unexperienced users and got me confused on a first read as well).

Kind regards
Lukas Willin

**Comment by karissa** [comment] 2018-05-01 01:28
Thanks @LukasWillin for reporting this. Which part exactly is like that (Can you take a screenshot)? Can you download the newest version of Mapeo and see if that's still the case?

**Comment by LukasWillin** [comment] 2018-05-01 18:52
Maybe I should first tell you that my system language is de-DE.

This screenshot is from the version 2.1.0 downloaded from https://www.digital-democracy.org/mapeo/:
![confusingsavedialog](https://user-images.githubusercontent.com/14276298/39487159-93587db8-4d7e-11e8-85ec-b22e186ae975.jpg)
Translatetd from german to english it reads: "Changes you upload as [?] will be available on all maps which use OpenStreetMap data".

I guess its because there is no localization for german defined in "locales/" and it uses the resources from the standard id-editor. Maybe you want to default to english if you dont support the language at this point of development.

Another weird occurence is that it shows a double space between "..as " and " will.." (marked with [?]). Probably there would be user name displayed.

**Comment by LukasWillin** [comment] 2018-05-10 20:33
Okay so I got it working with running the following in order
Deleting the node-modules folder and the package-lock.json
npm run install
npm run clean
npm rebuild leveldb
npm run dev

After that I checked on the save dialog but he is still stating the same thing:
![grafik](https://user-images.githubusercontent.com/14276298/39892804-1b04c594-54a2-11e8-986e-3289d93f8d73.png)

Any thoughts on this?

**Comment by karissa** [comment] 2018-05-10 20:57
This should be fixed here! Nice catch. I think the problem is that iD changed the way they were rendering that button. https://github.com/digidem/iD-mapeo/commit/eaad6cdbd888126806fc736401996b45cb8bf0b6

**Comment by LukasWillin** [comment] 2018-05-11 07:18
I just noticed that the text above the buttons is already fixed. (Didnt read it till the end) My Bad. So that works. Nice.

**Comment by karissa** [comment] 2018-09-21 20:59
Closing this since it seems resolved.

**Closed by karissa** 2018-09-21 20:59 UTC
