### ISSUE TITLE
GeoJSON export failed due to internal error

### ISSUE THREAD

**Issue by todrobbins** [digidem/mapeo-desktop#356] opened 2020-05-21 03:56 UTC
**Describe the bug**
When attempting to export GeoJSON in the `Territory` view, a JS error window appears and the export fails.

**Can you do the same thing twice?**
The exact steps to see the problem again.
1. Click on `...`
2. Click on `Export GeoJSON...`
3. See error

**Expected behavior**
Successfully export a GeoJSON file from the `Territory` view

**Screenshots**
<img width="532" alt="Screen Shot 2020-05-20 at 9 50 32 PM" src="https://user-images.githubusercontent.com/158590/82521616-5d7e4a00-9ae4-11ea-817a-c1f0a9d0c1c3.png">
<img width="500" alt="Screen Shot 2020-05-20 at 9 50 36 PM" src="https://user-images.githubusercontent.com/158590/82521618-5eaf7700-9ae4-11ea-88c1-dbb99c0d5197.png">

**Desktop:**
 - OS: macOS 10.15.4
 - Browser Mapeo Desktop
 - Version 5.2.1

**Comment by okdistribute** [comment] 2020-05-21 06:42
I think this is a duplicate of #318 !

**Comment by okdistribute** [comment] 2020-05-21 06:43
To create presets, use https://docs.mapeo.app/customization/preparing-mapeo-configuration

On my list this month is to make this better :) thanks for reporting!

**Closed by okdistribute** 2020-05-21 06:43 UTC
