### ISSUE TITLE
Uncaught Exception ReadError on Mac

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#40] opened 2016-10-04 03:08 UTC
Attempting to open the latest version on Mac gives the following error:

Uncaught Exception:
ReadError
    at /Applications/Mapeo.app/Contents/Resources/app/node_modules/levelup/lib/levelup.js:220:15

**Comment by noffle** [comment] 2016-10-04 16:54
Surprisingly, I am not able to reproduce! I ran [this build (DMG)](https://github.com/digidem/mapeo-desktop/releases/tag/v1.2.5) on my Macbook Air 13" (mid-2012) with macOS Sierra and it seems to work /wo issue.

**Comment by noffle** [comment] 2016-10-07 16:29
This should be fixed by https://github.com/digidem/mapeo-desktop/commit/ef0f43cb1573fa824d2103defdd645a3480d6891.

**Closed by noffle** 2016-10-07 16:29 UTC
